/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Demo;

//import com.sun.jdi.connect.spi.Connection;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
//import java.sql.DriverManager;
//import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author home
 */
public class Form extends javax.swing.JFrame {

    DefaultTableModel tbn = new DefaultTableModel();
    public Form() {
        initComponents();
        loadData();
    }
    public void loadData(){
        try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            int number;
            Vector row,column;
            column = new Vector();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from Nhanvien");
            ResultSetMetaData metadata = rs.getMetaData();
            number = metadata.getColumnCount();
            
            for(int i = 1;i <= number; i++){
                column.add(metadata.getColumnName(i));
            }
            tbn.setColumnIdentifiers(column);
            
            while (rs.next()){
                row = new Vector();
                for(int i = 1;i <= number; i++){
                    row.addElement(rs.getString(i));
                }
                tbn.addRow(row);
                jTable.setModel(tbn);
            }
            
            jTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){

                @Override
                public void valueChanged(ListSelectionEvent e) {
                   if(jTable.getSelectedRow() >=0){
                       txt_MaNV.setText(jTable.getValueAt(jTable.getSelectedRow(), 0) + "");
                       txt_TenNV.setText(jTable.getValueAt(jTable.getSelectedRow(), 1) + "");
                       txt_namSinh.setText(jTable.getValueAt(jTable.getSelectedRow(), 2) + "");
                       txt_sdt.setText(jTable.getValueAt(jTable.getSelectedRow(), 3) + "");
                       txt_soNC.setText(jTable.getValueAt(jTable.getSelectedRow(), 4) + "");
                   }
                }
            });
        }catch(Exception ex){
            System.out.print(ex.toString());
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_MaNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_TenNV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_namSinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        txt_luongCB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_NgayLT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_luongLT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_soNC = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_donGia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        tbn_TinhLuongNVFT = new javax.swing.JButton();
        tbn_TinhLuongNVPT = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txt_phuCap = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();

        jLabel14.setText("jLabel14");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("QUẢN LÝ TIỀN LƯƠNG NHÂN VIÊN");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Mã Nhân Viên");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Tên Nhân Viên");

        txt_TenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenNVActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Năm Sinh");

        txt_namSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namSinhActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Số Điện Thoại");

        txt_sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sdtActionPerformed(evt);
            }
        });

        txt_luongCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_luongCBActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("NHÂN VIÊN FULL TIME");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Lương Cơ Bản :");

        txt_NgayLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NgayLTActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Ngày Làm Thêm :");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Lương Làm Thêm :");

        txt_luongLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_luongLTActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("NHÂN VIÊN PAST TIME");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Ngày Công");

        txt_soNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soNCActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Đơn Giá :");

        txt_donGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_donGiaActionPerformed(evt);
            }
        });

        jTable.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân viên", "Tên Nhân viên", "Năm Sinh", "SDT", "Số Ngày Công", "Lương"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        tbn_TinhLuongNVFT.setText("Luong NVFT");
        tbn_TinhLuongNVFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_TinhLuongNVFTActionPerformed(evt);
            }
        });

        tbn_TinhLuongNVPT.setText("Luong NVPT");
        tbn_TinhLuongNVPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_TinhLuongNVPTActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Phụ Cấp :");

        txt_phuCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phuCapActionPerformed(evt);
            }
        });

        btn_them.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_namSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_soNC, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(178, 178, 178)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_luongCB, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(txt_NgayLT, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(txt_luongLT, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(txt_phuCap)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(tbn_TinhLuongNVFT)
                                .addGap(93, 93, 93)
                                .addComponent(tbn_TinhLuongNVPT)
                                .addGap(37, 37, 37)
                                .addComponent(btn_them)
                                .addGap(31, 31, 31)
                                .addComponent(btn_sua)
                                .addGap(33, 33, 33)
                                .addComponent(btn_xoa))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(jLabel1)))
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_donGia, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_luongCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_namSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NgayLT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_luongLT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_phuCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_soNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_donGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbn_TinhLuongNVPT)
                    .addComponent(tbn_TinhLuongNVFT)
                    .addComponent(btn_them)
                    .addComponent(btn_sua)
                    .addComponent(btn_xoa))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_TenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenNVActionPerformed

    private void txt_namSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namSinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namSinhActionPerformed

    private void txt_sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sdtActionPerformed

    private void txt_soNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soNCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soNCActionPerformed

    private void tbn_TinhLuongNVFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_TinhLuongNVFTActionPerformed
        //input
        String ma = txt_MaNV.getText();
        String ten = txt_TenNV.getText();
        int ns = Integer.parseInt(txt_namSinh.getText());
        int sdt = Integer.parseInt(txt_sdt.getText());
        int snc = Integer.parseInt(txt_soNC.getText());
        float lcb = Float.parseFloat(txt_luongCB.getText());
        float llt = Float.parseFloat(txt_luongLT.getText());
        float pc = Float.parseFloat(txt_phuCap.getText());
        int nlt = Integer.parseInt(txt_NgayLT.getText());
        //khoi tao doi tuong
        NVFT dh = new NVFT(ma,ten,ns,sdt,snc,lcb,llt,pc,nlt);
        //Show
        //thiet lap ten cot cho bang
        Vector tencot = new Vector();
        tencot.add("STT");
        tencot.add("Mã Nhân VIên");
        tencot.add("Tên Nhân Viên");
        tencot.add("Năm Sinh");
        tencot.add("SDT");
        tencot.add("Số Ngày Công");
        tencot.add("Lương");
        
        Vector data = new Vector();
        data.add(1);
        data.add(dh.getMaNV());
        data.add(dh.getTenNV());
        data.add(dh.getNamSinh());
        data.add(dh.getSdt());
        data.add(dh.getSoNC());
        data.add(dh.TinhLuong());
        
        Vector row = new Vector();
        
        row.add(data);
        
        jTable.setModel(new DefaultTableModel(row,tencot));
    }//GEN-LAST:event_tbn_TinhLuongNVFTActionPerformed

    private void tbn_TinhLuongNVPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_TinhLuongNVPTActionPerformed
        //input
        String ma = txt_MaNV.getText();
        String ten = txt_TenNV.getText();
        int ns = Integer.parseInt(txt_namSinh.getText());
        int sdt = Integer.parseInt(txt_sdt.getText());
        int snc = Integer.parseInt(txt_soNC.getText());
        float dg = Float.parseFloat(txt_donGia.getText());
        //khoi tao doi tuong
        NVPT tv = new NVPT(ma,ten,ns,sdt,snc,dg);
        //Show
        //thiet lap ten cot cho bang
        Vector tencot = new Vector();
        tencot.add("STT");
        tencot.add("Mã Nhân VIên");
        tencot.add("Tên Nhân Viên");
        tencot.add("Năm Sinh");
        tencot.add("SDT");
        tencot.add("Số Ngày Công");
        tencot.add("Lương");
        
        Vector data = new Vector();
        data.add(1);
        data.add(tv.getMaNV());
        data.add(tv.getTenNV());
        data.add(tv.getNamSinh());
        data.add(tv.getSdt());
        data.add(tv.getSoNC());
        data.add(tv.TinhLuong());
        
        Vector row = new Vector();
        
        row.add(data);
        
        jTable.setModel(new DefaultTableModel(row,tencot));
    }//GEN-LAST:event_tbn_TinhLuongNVPTActionPerformed

    private void txt_NgayLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NgayLTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NgayLTActionPerformed

    private void txt_donGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_donGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_donGiaActionPerformed

    private void txt_phuCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phuCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phuCapActionPerformed

    private void txt_luongCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_luongCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_luongCBActionPerformed

    private void txt_luongLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_luongLTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_luongLTActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        try {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            PreparedStatement pr = conn.prepareStatement("Delete Nhanvien where MaNV=?");
            pr.setString(1, jTable.getValueAt(jTable.getSelectedRow(), 0).toString());
            if(JOptionPane.showConfirmDialog(this,"Delete this Nhanvien?","Confirm",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                pr.executeUpdate();
                tbn.setRowCount(0);
                loadData();
            } 
        }catch (Exception ex){
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        try {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            PreparedStatement pr = conn.prepareStatement("insert into Nhanvien values (?,?,?,?,?)");
            pr.setString(1, txt_MaNV.getText());
            pr.setString(2, txt_TenNV.getText());
            pr.setString(3, txt_namSinh.getText());
            pr.setString(4, txt_sdt.getText());
            pr.setString(5, txt_soNC.getText());
            
            int chk = pr.executeUpdate();
            if(chk > 0){
                JOptionPane.showMessageDialog(this,"them thanh cong");
                tbn.setRowCount(0);
                loadData();
            }else{
                
            }
        }catch (Exception ex){
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            PreparedStatement pr = conn.prepareStatement("Update Nhanvien set TenNV=?,namSinh=?,sdt=?,soNC=? where MaNV=?");
            pr.setString(5, txt_MaNV.getText());
            pr.setString(1, txt_TenNV.getText());
            pr.setString(2, txt_namSinh.getText());
            pr.setString(3, txt_sdt.getText());
            pr.setString(4, txt_soNC.getText());
            pr.executeUpdate();
            tbn.setRowCount(0);
            loadData();
            
        }catch (Exception ex){
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JButton tbn_TinhLuongNVFT;
    private javax.swing.JButton tbn_TinhLuongNVPT;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_NgayLT;
    private javax.swing.JTextField txt_TenNV;
    private javax.swing.JTextField txt_donGia;
    private javax.swing.JTextField txt_luongCB;
    private javax.swing.JTextField txt_luongLT;
    private javax.swing.JTextField txt_namSinh;
    private javax.swing.JTextField txt_phuCap;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_soNC;
    // End of variables declaration//GEN-END:variables
}
